platform :ios, '13.0'

install! 'cocoapods',
:generate_multiple_pod_projects => true

plugin 'cocoapods-binary-cache'
config_cocoapods_binary_cache(
  cache_repo: {
    "default" => {
      "local" => "~/.cocoapods-binary-cache/PodBinaryCacheExample-libs"
    }
  },
  prebuild_config: "Release",
  xcframework: true,
  device_build_enabled: true,
  build_args: {
    :simulator => [
      "ARCHS='x86_64 arm64'"
    ],
    default: ["MACH_O_TYPE=staticlib"]
  }
)




target 'PodBinCacheExample' do
  use_frameworks!
  
  pod 'AFNetworking', '3.2.1', :binary => true
  pod 'SDWebImage', :binary => true
  pod 'SnapKit', :binary => true
  pod 'Kingfisher', :binary => true
end

# AI 错误：       39 -      pod_target.native_target.build_configurations.each do |config|
# AI 发现错误修正：⏺ 我看到了错误。pod_target 对象没有 native_target 方法。让我修正这个问题：

post_install do |installer|
  # 当使用 generate_multiple_pod_projects 时，需要遍历所有 generated projects
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES' # Only work from Xcode 11
        if Gem::Version.new('13.0') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
      end
    end
  end
end