name: test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Ruby setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: RSpec
        run: |
          bundle exec rspec spec

  integration_test:
    runs-on: macOS-latest
    strategy:
      matrix:
        mode: [afnetworking-switch, dev-pod-switch]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Ruby setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Bundle installation (example)
        working-directory: PodBinaryCacheExample
        run: |
          bundle install
      - name: Integration tests
        run: |
          sh scripts/integration_test.sh ${{matrix.mode}}
